version: '3.8'

services:
  # main:
  #   container_name: server
  #   build:
  #     context: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - 5000:5000
  #     - 9229:9229
  #   command: npm run start:dev
  #   depends_on:
  #     - postgres
  #   restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5555:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:

